name: Build Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build for Windows
      if: matrix.platform == 'win'
      run: npm run build:win
    
    - name: Build for macOS
      if: matrix.platform == 'mac'
      run: npm run build:mac
    
    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: npm run build:linux
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-mcp-server-${{ matrix.platform }}
        path: dist/